### ISSUE TITLE
Recieving error using this package.

### ISSUE THREAD

**Issue by pipoblak** [robfallows/tunguska-reactive-aggregate#1]
Hi, i'm receiving error after a time using this package:
```
Exception from sub schedules.aggregate id DhS6c9s5eZ8RrQXGK MongoError: exceeded maximum query tree depth of 100 at {}
I20180317-19:52:20.031(-3)?     at Function.MongoError.create (/Users/feliperamos/.meteor/packages/npm-mongo/.2.2.34.1y0a3f1.nmrr++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/error.js:31:11)
I20180317-19:52:20.031(-3)?     at queryCallback (/Users/feliperamos/.meteor/packages/npm-mongo/.2.2.34.1y0a3f1.nmrr++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/cursor.js:212:36)
I20180317-19:52:20.032(-3)?     at /Users/feliperamos/.meteor/packages/npm-mongo/.2.2.34.1y0a3f1.nmrr++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:469:18
I20180317-19:52:20.032(-3)?     at _combinedTickCallback (internal/process/next_tick.js:131:7)
I20180317-19:52:20.032(-3)?     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
I20180317-19:52:20.032(-3)?  => awaited here:
I20180317-19:52:20.032(-3)?     at Function.Promise.await (/Users/feliperamos/.meteor/packages/promise/.0.10.2.2y2yly.4208m++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20180317-19:52:20.033(-3)?     at Promise.asyncApply (packages/tunguska:reactive-aggregate/aggregate.js:19:13)
I20180317-19:52:20.033(-3)?     at /Users/feliperamos/.meteor/packages/promise/.0.10.2.2y2yly.4208m++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20180317-19:52:20.033(-3)?  => awaited here:
I20180317-19:52:20.033(-3)?     at Function.Promise.await (/Users/feliperamos/.meteor/packages/promise/.0.10.2.2y2yly.4208m++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20180317-19:52:20.033(-3)?     at ReactiveAggregate (packages/tunguska:reactive-aggregate/aggregate.js:56:3)
I20180317-19:52:20.033(-3)?     at Subscription._handler (server/publications.js:30:5)
I20180317-19:52:20.033(-3)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20180317-19:52:20.034(-3)?     at DDP._CurrentPublicationInvocation.withValue (packages/ddp-server/livedata_server.js:1043:15)
I20180317-19:52:20.034(-3)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:26)
I20180317-19:52:20.034(-3)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1041:51)
I20180317-19:52:20.034(-3)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:859:9)
I20180317-19:52:20.034(-3)?     at Session.sub (packages/ddp-server/livedata_server.js:625:12)
I20180317-19:52:20.034(-3)?     at packages/ddp-server/livedata_server.js:559:43
```
The package works great, but after a time consuming the data, and refreshing, the subscriptions stop to work and i receive this error from Server.

**Comment by robfallows** [comment]
Hmm. That *looks* like an internal MongoDB library error, not a Meteor or package error.

When you say "and refreshing" - what do you mean?

**Comment by pipoblak** [comment]
I noticed this problem when the data from the server stop working after some time, and making some tests i realize that:
1 - Subscriptions overflowing ( When i reach 20 subscriptions of the same collection with reactive aggregate ( Doesn't matter if i stop past subscriptions))
2 - Analysing that , i guess this have something to do with storing data on the "sub", because the server is logging me a overflow problem.

By "and refreshing" , i mean that the subscription is being re-created . 

Thats the code of my template onCreated and OnDestroyed:

`Template.spaceSite.onDestroyed(function(){
  this.eventsSubscription.stop();
  this.scheduleSubscription.stop();
})
Template.spaceSite.onCreated(function(){
  this.data = Template.currentData();
  this.selected_space=ReactiveVar();
  this.eventsSubscription=Meteor.subscribe("events.aggregate");
  this.scheduleSubscription=Meteor.subscribe("schedules.aggregate");
});`

**Comment by robfallows** [comment]
That error is because the MongoDB engine recursively processed a document with more than 100 levels of nesting. The pipeline lets you redefine documents as they pass through the various stages. It's possible that your aggregation pipeline has a breaking step.

https://jira.mongodb.org/browse/SERVER-13661

**Comment by pipoblak** [comment]
Thats the pipeline who i'm using:
```
[
  {
    $lookup: {
      from:"schedules",
      localField: 'schedule_id',
      foreignField: '_id',
      as: 'schedule',
      }
  },
  {$unwind:"$schedule"},
  {
    $lookup: {
      from:"positions",
      localField: 'schedule.positions_id',
      foreignField: '_id',
      as: 'positions',
    }
  },
  {
    $lookup: {
      from:"spaces",
      localField: 'space_id',
      foreignField: '_id',
      as: 'space',
    }
  },
  {$unwind:"$space"}
]
```

It works great, but when i reach a number of subscriptions with this, the package start to log me errors :/ i really don't know what is making it happens. It works for first 20~30 subscriptions.... but when we are in the 20 subscription it stops :(

**Comment by pipoblak** [comment]
The strange is, all works great, but when i reach a certainly number of subscriptions with reactive aggregate in a Collection, i reach in this problem, and need to restart the server to work again.

**Comment by robfallows** [comment]
Are the collections and/or documents large?

There are limits on document size of 16MB and pipeline stage of 100MB.

These are pretty big numbers, but an array of documents from `$lookup` could easily break the 16MB limit.

**Comment by robfallows** [comment]
You could try

- `meteor remove tunguska:reactive-aggregate`
- `meteor add jcbernack:reactive-aggregate`

and change any `import` statements you have.

**Comment by pipoblak** [comment]
I found the problem `:D,  i update my mongo DB Server Version to 3.6.3, and all works fine now!

Thanks for your attention, and your package.
