### ISSUE TITLE
Aggregation results in all documents being fetched from collection via observers. Is that expected behavior?

### ISSUE THREAD

**Issue by jamauro** [robfallows/tunguska-reactive-aggregate#11]
Hi @robfallows,

Thanks for putting this package together. I added it recently to do some aggregate counting. One thing I noticed is it looks like the aggregation results in all documents from the collection being fetched via observers even though I'm matching on a subset.

Is that to be expected? Appreciate any insight you might have.

**Comment by robfallows** [comment]
I'm not completely sure what you're doing/expecting.

Are you able to share your code or put together a minimal reproduction?

The steps the package goes through are:

1. Run an initial aggregation on the supplied collection. It's up to the aggregation pipeline to select the documents to be processed (e.g. by using `$match`).
1. The resulting documents from the aggregation are then added to the clientside collection.
1. An observer is set up which looks for change documents in the collection. This observer may be fine-tuned with the `observeSelector` and `observeOptions` properties of the aggregation `options`. It's probably a good idea to mimic your aggregation's `$match` selector here, or all documents will be observed.
1. Any qualifying document changes cause a re-run of the aggregation from the top (the whole process effectively begins again from 1).

If you want even more control, you could take a look at PR #10.

**Comment by jamauro** [comment]
Ah, I was missing # 3 so all documents were being observed. Thanks for pointing me in the right direction.

I like the concepts in PR #10 as well. I had assumed that any Collection involved in a `$lookup` would be reactive as well after reading the `jcbernack:reactive-aggregate` docs.
