### ISSUE TITLE
ObjectIDs in documents from $lookup aggegation are of form { _bsontype: "ObjectID", id: Uint8Array() }

### ISSUE THREAD

**Issue by ShaggyKris** [robfallows/tunguska-reactive-aggregate#18]
![image](https://user-images.githubusercontent.com/7747148/63700051-00bd5f80-c7f0-11e9-8138-d0ba08f97c6a.png)

How can I get it to either be projected as a string or the original ObjectID format? Currently, any document I use a `$lookup` operation on will result in having the above format. Also the id isn't anywhere near the same as it is when I look at it in the database.

**Comment by robfallows** [comment]
Have you tried https://docs.mongodb.com/manual/reference/operator/aggregation/toObjectId/

**Comment by robfallows** [comment]
I don't think this is an issue specifically to do with this package, which just takes what the MongoDB JavaScript library returns. However, if you can supply a minimal reproduction (i.e I can just clone and run), I will see if anything can be done in the package to mitigate.
