### ISSUE TITLE
"aggregation document _id is not an allowed type" on numeric _id

### ISSUE THREAD

**Issue by cormip** [robfallows/tunguska-reactive-aggregate#22]
Error is thrown if projecting numeric _id's despite the fact that numeric values are an allowed type by MongoDB. From the [manual](https://docs.mongodb.com/v4.0/core/document/):

> The field name _id is reserved for use as a primary key; its value must be unique in the collection, is immutable, and may be of any type other than an array.

**Comment by robfallows** [comment]
This is a limitation of the Meteor implementation. Numeric `_id`s are coerced into strings: <https://github.com/meteor/meteor/blob/d8042c8fa9dd0cc53604b2729ac33333a2ce5b73/packages/mongo-id/id.js#L79-L81>.

However, I don't enforce the convention of `~<number>`. If you want to change the way the conversion to string is performed, you can do this in the pipeline.
