### ISSUE TITLE
Connot add to project METEOR@1.8.1

### ISSUE THREAD

**Issue by mahadoang** [robfallows/tunguska-reactive-aggregate#28]
METEOR@1.8.1
meteor add tunguska:reactive-aggregate

While checking for tunguska:reactive-aggregate@1.2.2:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

Thank you.

**Comment by robfallows** [comment]
@mahadoang : Thanks for spotting this. It seems the publish of the new version hung and never completed properly. I've had to bump the version to 1.2.3 and re-publish. That now works for me.

Note that if your meteor cache hasn't refreshed from the package server (it should have by now), you may need to `meteor add tunguska:reactive-aggregate@1.2.3`

**Comment by mahadoang** [comment]
@robfallows  Thank you.
