### ISSUE TITLE
observers not triggering rerun?

### ISSUE THREAD

**Issue by ggerber** [robfallows/tunguska-reactive-aggregate#32]
Hi Rob,
I am using the meteor/roles together with tunguska-reactive-aggregate.
I have the following publication that does not rerun, upon a change in Meteor.roleAssignment.

The change is made by:
Roles.addUsersToRoles('XStpb2oY4LmGWMKMy', ['admin'], systemId);

I can confirm that the document count increases in the mongo console with this:
db['role-assignment'].find({'user._id':'XStpb2oY4LmGWMKMy'}).count()

Am I using the observer option correctly?
```
import {Meteor} from 'meteor/meteor';
import {Roles} from 'meteor/alanning:roles';
import {ReactiveAggregate as reactiveAggregate} from 'meteor/tunguska:reactive-aggregate';
import Systems from '../collections/server/Systems';

Meteor.publish('systems.list', function systemslist() {
  if (this.userId) {
    const pipeline = [
      {
        $match: {
          _id: {
            $in: Roles.getScopesForUser(this.userId)
          }
        }
      },
      {
        $project: {
          name: 1
        }
      }
    ];
    const options = {
      clientCollection: 'ManageSystems',
      observers: [Meteor.roleAssignment.find({'user._id': this.userId})] // observer does not trigger re-run???!!!
    };
    reactiveAggregate(this, Systems, pipeline, options);
  } else this.ready();
});
```

**Comment by robfallows** [comment]
It looks OK syntactically.

I'd start by adding `debug: true` to the options and simplifying the observer find to `Meteor.roleAssignment.find()`

**Comment by ggerber** [comment]
Hi Rob,

I think this issue can be closed. My bad.
My original implementation used 2x observers, while I only required 1xobserver and a lookup. So I probably made this more complex than required.

I like the debug option. Is shows you how many times the database is actually being used.

Thanks
