### ISSUE TITLE
Converting ObjectID _id to a string?

### ISSUE THREAD

**Issue by RealHandy** [robfallows/tunguska-reactive-aggregate#34]
I just installed and used this package and it works exactly how I needed -- awesome! It does, however, seem to be converting my _ids from being ObjectIDs to being strings when the data is received at the client. Does that sound like something it could be doing? 

Thanks!

**Comment by robfallows** [comment]
Yep. There's a comment in the code to that effect:

<https://github.com/robfallows/tunguska-reactive-aggregate/blob/master/aggregate.js#L103-L110>

That was a pragmatic decision at the time to simplify the mechanism for tracking changes. It's certainly something I'd consider reviewing a PR to improve.

**Comment by RealHandy** [comment]
K. Thanks for the quick reply!

**Comment by RealHandy** [comment]
Created PR https://github.com/robfallows/tunguska-reactive-aggregate/pull/35 for your consideration. Thanks!

**Comment by RealHandy** [comment]
This is fixed in 1.3.
