### ISSUE TITLE
Reduce number of warnings due to missing simpl-schema dependency

### ISSUE THREAD

**Issue by faburem** [robfallows/tunguska-reactive-aggregate#40]
Hi,
while it's great to understand why Mongo.ObjectID support is disabled without using the simpl-schema dependency, it is really spamming the console in development:
<img width="804" alt="Screenshot 2020-04-20 at 15 59 57" src="https://user-images.githubusercontent.com/11456790/79760413-4cdd8700-8320-11ea-98d8-8195a2b47795.png">
Is there any chance we can reduce this to only one message? I would not want to remove it completely as it is definitely helpful in other situations.

Thanks for your feedback,
Fabian

**Comment by robfallows** [comment]
@faburem : That sounds like a good idea. Would you like to submit a PR?

**Comment by faburem** [comment]
done, [PR](https://github.com/robfallows/tunguska-reactive-aggregate/pull/41) submitted.

**Comment by robfallows** [comment]
Closed by #41

**Comment by RealHandy** [comment]
Thanks for that, @faburem -- I bet it was annoying!
