### ISSUE TITLE
Usage as a replacement for reactive joins (publishComposite)

### ISSUE THREAD

**Issue by jamauro** [robfallows/tunguska-reactive-aggregate#42]
Hi @robfallows, this is more of a question than an issue :)

Thanks for the great package. I've been using it to do reactive counting. I'm considering using it to do reactive joins on 3 collections to replace [publishComposite](https://github.com/Meteor-Community-Packages/meteor-publish-composite) so that I can return named collections to the client and I assume increase efficiency.

Are there any issues that I should be aware of or would you recommend not using it for that use case?

**Comment by robfallows** [comment]
@jamauro : I've not done any comparisons between the relative performance of `reactive-aggregate` vs `publish-composite`, so my opinion's not worth anything! If you are interested in doing a comparison, I'd be interested in the outcome. You should also look at [grapher](https://atmospherejs.com/cultofcoders/grapher), which takes a different and allegedly more performant approach to solve this use case.

**Comment by robfallows** [comment]
Closing. No further action.
