### ISSUE TITLE
Hide 'ReactiveAggregate support for Mongo.ObjectID is disabled due to 1 package error'

### ISSUE THREAD

**Issue by ggerber** [robfallows/tunguska-reactive-aggregate#43]
Hi Rob,

I use strings for my document ids, hence I do not have the issue of converting between strings and ObjectIds.

It is a bit annoying during the running of my app to see my console fill up with repeated:
I20200514-16:28:25.606(2)? ReactiveAggregate support for Mongo.ObjectID is disabled due to 1 package error(s):
I20200514-16:28:25.607(2)?    1 - simpl-schema: MODULE_NOT_FOUND

Is there an option to hide this message?
It makes error logging a bit more difficult if this package acts verbose

**Comment by robfallows** [comment]
@ggerber : That should be fixed in the latest version (1.3.2). Can you check you are using that version, please?

**Comment by ggerber** [comment]
I was using an older version.
I updated to 1.3.2 and now it only warns once.
Thanks

**Comment by robfallows** [comment]
Excellent! Thanks for checking and the feedback 👍
