### ISSUE TITLE
Remove warning: simpl-schema: MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by diavrank** [robfallows/tunguska-reactive-aggregate#44]
Hi, I think that the following warning shouldn't be present since I don't use **simpl-schema** package:

```
I20200721-17:13:55.983(5.5)? ReactiveAggregate support for Mongo.ObjectID is disabled due to 1 package error(s):
I20200721-17:13:55.984(5.5)? 1 - simpl-schema: MODULE_NOT_FOUND
```

**Comment by robfallows** [comment]
I've published a new version (1.3.3) which allows you to suppress these warning messages. Just set `options.warnings: false` (see the README for more information).

**Comment by diavrank** [comment]
Hi @robfallows , this feature still is in `supress-warning` branch. I guess I should wait for it to be on the master branch

**Comment by robfallows** [comment]
Good call. Asleep at the wheel!
