### ISSUE TITLE
Rerun Publication using a button in client

### ISSUE THREAD

**Issue by ralphievolt** [robfallows/tunguska-reactive-aggregate#46]
First of all thank you for this amazing package.

How can I re run this publication using a button in the client?  Or like running this every 10 minutes

```
Meteor.publish("biographiesByWelshAuthors", function () {
  ReactiveAggregate(this, Authors, [{
    $lookup: {
      from: "books",
      localField: "_id",
      foreignField: "author_id",
      as: "author_books"
    }
  }], {
    noAutomaticObserver: true
  });
});
```
Thank you.

**Comment by robfallows** [comment]
Running every 10 minutes is fairly straightforward:

```js
Meteor.publish("biographiesByWelshAuthors", function () {
  ReactiveAggregate(this, Authors, [{
    $lookup: {
      from: "books",
      localField: "_id",
      foreignField: "author_id",
      as: "author_books"
    }
  }], {
    debounceDelay: 600000,  // Re-run every 600 seconds
    noAutomaticObserver: true
  });
});
```

Re-running on a button is slightly more complex. Currently, you would need to define an observer on an unrelated collection. You would then use the button to trigger a change on that collection, which would re-run the aggregation.

A "cleaner" way to aggregate on demand may be an opportunity for a PR!

**Comment by ralphievolt** [comment]
Hi sorry for not closing this issue earlier.. I'll look into it using on demand. aggregation.

By the way is there a feature in a normal Publish to run it once like `noAutomaticObserver: true` 

Although I can use ReactiveAggregative for normal query but is an expensive query as what I've read

**Comment by ralphievolt** [comment]
Hi Rob,

Here's my subscription code:

```
export default withTracker((props) => {
  const handler = Meteor.subscribe("OrdersList");
  const isDataLoading = !handler.ready();
  const access = Meteor.user().roles;

  let ordersData;

  if (access[0].value === "cashier") {
    ordersData = Orders.find({
      status: {
        $in: ["ORDER_ON_GOING", "ORDER_IN_CART", "ORDER_CHECKED_OUT"],
      },
    }).fetch();
  } else if (access[0].value === "receptionist") {
    ordersData = Orders.find({
      status: { $in: ["ORDER_CREATED", "VERIFYING"] },
    }).fetch();
  } else if (access[0].value === "admin") {
    ordersData = Orders.find({
      status: {
        $in: [
          "ORDER_CREATED",
          "VERIFYING",
          "ORDER_ON_GOING",
          "ORDER_IN_CART",
          "ORDER_CHECKED_OUT",
        ],
      },
    }).fetch();
  }

  return {
    ordersData,
    isDataLoading,
  };
})(CustomersListComponent);
```

and my publish function

```
Meteor.publish("OrdersList", function () {
  const startD = moment(new Date()).subtract(30, "Days").toDate();
  const endD = new Date();
  endD.setHours(23, 59, 59);

  const dateRangeAgg = {
    $match: {
      created_at: {
        $gte: startD,
        $lte: endD,
      },
    },
  };
  ReactiveAggregate(
    this,
    Orders,
    [
      dateRangeAgg,
      openOrder,
      custProfile,
      unwindProfile,
      sorter,
      {
        $project: {
          _id: 1,
          customer_id: 1,
          firstname: 1,
          middlename: 1,
          lastname: 1,
          transaction_type: 1,
          status: 1,
          created_at: 1,
          verified_by: 1,
          "customer_profile.payment_source": 1,
          "customer_profile.gender": 1,
          "customer_profile.birthdate": 1,
        },
      },
    ],
    {
      // debounceDelay: 300000, // Re-run every 5 minutes
      debounceDelay: 30000, // Re-run every 5 minutes
      noAutomaticObserver: true,
    }
  );
});
```

but I observed that my subscription in minimongo was not updating after the `debounceDelay` when an a new order was updated.

**Comment by robfallows** [comment]
Apologies for the delay - long Christmas break!

You need to make an amendment to your options. Instead of:

```js
{
  debounceDelay: 30000, // Re-run every 5 minutes
  noAutomaticObserver: true,
}
```

Use:

```js
{
  debounceCount: Infinity,  // Needed or the default 0 will override the delay
  debounceDelay: 300000, // Re-run every 5 minutes
  noAutomaticObserver: true,
  observers: [
    Orders.find()  // You could refine this, but this is the minimum
  ],
}
```

**Comment by ralphievolt** [comment]
Happy New Year.

Okay I will  try this.

Anyway, for normal Publish, no aggregation, is there an option to run like very 5 minutes also?

**Comment by robfallows** [comment]
> Anyway, for normal Publish, no aggregation, is there an option to run like very 5 minutes also?

It depends on your definition of "normal". You can do this if you make use of the [pub/sub API](https://docs.meteor.com/api/pubsub.html#Subscription-added): `added`, `changed`, `removed`, `ready`. You can't do it with a MongoDB query publication, which I suspect is what you're after using.

You could do this from the client if you forego pub/sub and use Meteor methods by putting a `Meteor.call` inside a `setInterval` callback on the client. That technique would also give you on-demand re-running.

**Comment by ralphievolt** [comment]
Rob, the ReactiveAggregate now works as expected with a little refined observers...

Last question though....

I'm too lazy to create a `Method.call `during a `componentDidMount` **just to get a data from server once**. Is it possible to use
`withTracker + Pub/Sub`?  Meaning I only subscribe to the data once, basically no reactivity =) If yes, how?

I am actually  rewriting my code to reduce Server Memory because of all the reactivity I put in. Perhaps I didn't realize it then

**Comment by DeanKamali** [comment]
That's mentioned in the documentation, "**Non-Reactive Aggregations**" 
Like a Meteor Method, but the results come back in a Minimongo collection.

```
Meteor.publish("biographiesByWelshAuthors", function () {
  ReactiveAggregate(this, Authors, [{
    $lookup: {
      from: "books",
      localField: "_id",
      foreignField: "author_id",
      as: "author_books"
    }
  }], {
    noAutomaticObserver: true
  });
});
```
No observers were specified and noAutomaticObserver was enabled, so the publication runs once only.

**Comment by ralphievolt** [comment]
@DeanKamali , I am not referring to an aggregation but a simple Publish query running once only.

**Comment by DeanKamali** [comment]
@ralphievolt not really seeing a big difference, running “simple query” or using aggregation framework to run the same query. 

I use aggregation framework with all of my publications, for the sake of consistency, and flexibility of using custom client collection names.

To answer your question, I’m not really sure, It would be more appropriate to use meteor methods, or a hacky way on the server side, maybe wrap your query with if statement so that it returns only once.

**Comment by robfallows** [comment]
Meteor publications are not reactive. What that means is that the client has to explicitly cause the publication to re-run if the publication is to change its behaviour. Put another way, once set up, a publication continues to publish the documents it was set up for *unless the client changes the request*.

Your options are:

1. Continue to use the `reactive-aggregate` package.
2. Switch to Meteor methods.
3. Code a bespoke variant of a "normal" publication using the pub/sub api.

**Comment by ralphievolt** [comment]
Thank you guys for the inputs.
