### ISSUE TITLE
Removing from collection causes an error

### ISSUE THREAD

**Issue by olafsozanski** [robfallows/tunguska-reactive-aggregate#48]
It might be similar to issue #14 .

I create really simple aggregation:
```
ReactiveAggregate(this, Tasks, [

])
```

I get an error when removing anything from database with CLI:
```
Exception in removedobserveChanges callback: errorClass [Error]: Removed nonexistent document -6004623726092158e67a4ae4
```

Document ID is "6004623726092158e67a4ae4".

**Comment by robfallows** [comment]
What version of Meteor are you using?

**Comment by olafsozanski** [comment]
I am using Meteor 1.12.1.
One additional thing: the problem appears only in CLI.

**Comment by robfallows** [comment]
What exactly do you mean by CLI - `meteor mongo` or something else?

**Comment by robfallows** [comment]
^^ @olafsozanski : Can you answer the above, please?

**Comment by olafsozanski** [comment]
1. Yes, it happens when i use `mongo meteor`.
2. With empty pipeline and with non-empty pipeline, too.
3. In dev.

**Comment by robfallows** [comment]
I have written a small test using Meteor 1.12.1 and an empty pipeline. I cannot reproduce your problem.

If you can put together a small repo which demonstrates what you are seeing, I'll take a look.

**Comment by valerymagadeeva** [comment]
Hi! Faced to this problem again. Meteor 2.16, package version is 1.3.16. I use async publication, probably it causes the problem
