### ISSUE TITLE
remove underscore dependency

### ISSUE THREAD

**Issue by ggerber** [robfallows/tunguska-reactive-aggregate#5]
This package uses _.extend()
Is it possible to remove the underscore dependency by replacing:
_.extend()
with
const mergedOptions = Object.assign(defaultOptions, options)
?

IMO this package is a gem crafted by a wizard.
It is a pity it is not mentioned in the the meteor docs, as I only stumbled upon it by chance in the forums.

**Comment by robfallows** [comment]
@ggerber : please submit a PR 🙂

**Comment by robfallows** [comment]
@ggerber : I'm going to address this slightly differently by using the `...` operator: #10.

Still a work-in-progress, as it has a number of other improvements.

**Comment by ggerber** [comment]
Cool Merlin!

**Comment by robfallows** [comment]
@ggerber : PR #10 is ready for review.

I'd appreciate it if you could review/test. Instructions are in the PR.

Thank you 🙂

**Comment by robfallows** [comment]
@ggerber : bumping ^^

**Comment by ggerber** [comment]
Hi Rob,

I plan to take your new version for a spin next week to see how it runs.

Best regards,
George
