### ISSUE TITLE
False error complaining that lodash is missing when not using Mongo ObjectIds

### ISSUE THREAD

**Issue by softwarecreations** [robfallows/tunguska-reactive-aggregate#64]
## EDIT:
Ok I just found this old issue:
https://github.com/robfallows/tunguska-reactive-aggregate/issues/44
(with solution to specify)
`options.warnings:false`
This does indeed work for suppressing warnings regarding simpl-schema and lodash...

While that's better than nothing, it would be nice to suppress only the Mongo.ObjectId related warnings, not all other and future possible warnings. That could be dangerous, is overkill and could make debugging future possible problems unnecessarily difficult.

---------------------
The premise of this issue is that we're getting an unnecessary warning against doing something that we aren't doing.
--------------

## Issue that I wrote before I found the above issue

Hi thanks very much for sharing this awesome module,

This is a low priority issue, but just sharing the details:

I do not use Mongo ObjectIds anywhere in my entire database. I use Meteor style string _id's generated by Meteor or `Random.id()`

Because of this I expected that I don't need to install simpl-schema or lodash or lodash-es NPM modules.

I wrote some server-side code that do some simple aggregations a few months ago. I've not changed that code since I initially wrote it.
It looks like I installed `simpl-schema` at the time to get rid of (false?) errors from tunguska-reactive-aggregate
For months I've not had any errors.

But lately I'm getting this error
   1 - lodash-es or lodash: lodash-es(MODULE_NOT_FOUND), lodash(Error: Cannot find module "/node_modules/lodash/set.js". Try installing the npm package or make sure it is not a devDependency.)
   
The error goes away if I do `npm i --save lodash` but does not go away if I do `npm i --save-dev lodash` or `npm i --save-dev lodash-es`
and comes back.

Additionally, if I remove both lodash and simpl-schema then it complains about both being missing.
```
ReactiveAggregate support for Mongo.ObjectID is disabled due to 2 package error(s):
   1 - lodash-es or lodash: lodash-es(MODULE_NOT_FOUND), lodash(Error: Cannot find module "/node_modules/lodash/set.js". Try installing the npm package or make sure it is not a devDependency.)
   2 - simpl-schema: MODULE_NOT_FOUND
```

tunguska-reactive-aggregate Readme Reference
https://github.com/robfallows/tunguska-reactive-aggregate#mongoobjectid-support

I understand that this might be a friendly warning, but it's very disruptive seeing my console filled up with this false warning every time I hit save (hundreds of times a day sometimes) it would be nice if we can silence these warnings via some option.

Related closed issues
https://github.com/robfallows/tunguska-reactive-aggregate/issues/40
https://github.com/robfallows/tunguska-reactive-aggregate/issues/43

**Comment by robfallows** [comment]
Thanks for the feedback. However...

> ...it would be nice if we can silence these warnings via some option.

https://github.com/robfallows/tunguska-reactive-aggregate#usage (`warnings` option):

>   - `warnings`: A boolean (`true` or `false`) which controls the logging of warning messages. Defaults to `true` (warning messages are logged).

**Comment by softwarecreations** [comment]
Hi @robfallows thanks very much for your reply!

Sorry I didn't think of looking at closed issues before creating the issue, Please see my edit at the top of the issue?

**Comment by robfallows** [comment]
No worries. I like the easy issues :wink:

**Comment by softwarecreations** [comment]
Amazing 8D

**Comment by softwarecreations** [comment]
Does that mean you're adding an option to suppress Mongo.ObjectId related warnings specifically
(but not suppress other warnings)
?

**Comment by softwarecreations** [comment]
I think it's a necessary option to add, considering
* The normal/default way to use Meteor is to use Meteor ID's, meaning almost everybody is going to run into this.
* This is the 4th issue about this problem, it's only going to continue.
(probably best to mention it in the Mongo.ObjectId Readme section to save people time and avoid further issues)
https://github.com/robfallows/tunguska-reactive-aggregate#mongoobjectid-support

**Comment by robfallows** [comment]
Please submit a PR.

**Comment by softwarecreations** [comment]
Thanks

https://github.com/robfallows/tunguska-reactive-aggregate/pull/65
