### ISSUE TITLE
ReactiveAggregate not working with $lookup

### ISSUE THREAD

**Issue by AlanOrtega91** [robfallows/tunguska-reactive-aggregate#9]
When using `$lookup` the other collections is not reactive

**Comment by robfallows** [comment]
That's true and it's a valid use case.

It seems that this could be done by either:

- examining the pipeline for "other" collections and adding those to the observer, or
- an additional parameter/option to allow the caller to specify which other collections should be observed.

My personal preference is the first. I can take a look at adding that behaviour, but my time's a bit limited at the moment. Alternatively, you could submit a PR.

**Comment by AlanOrtega91** [comment]
I´ll see if I can create that PR in my spare time.
Thanks!

**Comment by robfallows** [comment]
@AlanOrtega91 : I've found some time to make a start on this, along with some other improvements: #10.

Still a work-in-progress atm.

**Comment by robfallows** [comment]
@AlanOrtega91 : PR #10 is ready for review.

I'd appreciate it if you could review/test. Instructions are in the PR.

Thank you 🙂

**Comment by robfallows** [comment]
@AlanOrtega91 : bumping ^^

**Comment by DeanKamali** [comment]
@AlanOrtega91  bumping!
